name: cpp-cmake-msvc2019-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-2019
    env:
      msvc2019TargetZip: winrt-playground-${{ github.ref_name }}-msvc2019.zip
    steps:
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: curl cmake-3.24.0-windows-x86_64.zip
        shell: cmd
        run: cd /d ${{ github.workspace }} && curl https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-x86_64.zip -L --output cmake-3.24.0-windows-x86_64.zip && dir && 7z.exe x cmake-3.24.0-windows-x86_64.zip
        
      - name: check dir
        shell: cmd
        run: dir
        
      - name: set PATH for cmake and especially nuget.exe, cmake generate and build
        shell: cmd
        run: |
            set PATH=${{ github.workspace }};^
            ${{ github.workspace }}\cmake-3.24.0-windows-x86_64\bin;^
            cmake.exe -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -B./build &&^
            cd build && cmake --build . --target ALL_BUILD --config Debug -- /nologo /verbosity:minimal /maxcpucount
            
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "${{github.workspace}}/build"
          filename: "${{ env.msvc2019TargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{github.workspace}}/build/${{ env.msvc2019TargetZip }}"
          allowUpdates: true
